[project]
name = "vsu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "h5py>=3.15.1",
    "plotext>=5.3.2",
    "pyyaml>=6.0.3",
    "rich>=14.2.0",
]
